config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :order_items, only: [:create, :destroy]
  resources :orders
  resources :carts
  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile', password: 'secret', confirmation: 'confirmations', unlock: 'unblock', registration: 'register', sign_up: ''},
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations', sessions: 'users/sessions' }

  root 'pages#home', as: :root
  get 'login/create', to: 'logins#create', as: :create_login

  resources :users do
    member do
      post :enable_multi_factor_authentication, to: 'users/multi_factor_authentication#verify_enable'
      post :disable_multi_factor_authentication, to: 'users/multi_factor_authentication#verify_disabled'
    end
  end

  # concern :paginatable do
  #   get '(page/:page)', :action => :index, :on => :collection, :as => ''
  # end

  # concern :paging_category do
  #   get '(/:id/page/:page)', :action => :show, :on => :collection, :as => ''
  # end

  # resources :categories, :concerns => :paging_category do
  #   resources :products
  # end

  resources :categories do
    resources :products
  end

  # resources :products, :concerns => :paginatable

  get 'check-user' => 'users#check_user'
  
  #search
  post 'products/search' => 'products#search', as: :products_search

  # sort
  post '/products/sort/price-up' => 'products#price_up', as: :products_sort_up
  post '/products/sort/price-down' => 'products#price_down', as: :products_sort_down

  post '/order_items/up/:id' => 'order_items#increment_quantity'
  post '/order_items/down/:id' => 'order_items#decrement_quantity'

  post '/carts/send_confirm_order' => 'carts#send_confirm_order', as: :cart_send_confirm_order

  get '/cart-confirm-auth' => 'carts#confirm_auth', as: :confirm_auth
  get '/cart-confirm-email' => 'carts#confirm_email'

  get 'orders/history' => 'orders#history', as: :orders_history

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_items, dependent: :destroy

  def items_count
    number_items = 0
    self.order_items.each do |item|
      number_items += item.quantity
    end
    if number_items < 10
      '0' + number_items.to_s
    else
      number_items.to_s
    end
  end
  
  def add_item(product_id)
    current_item = self.order_items.find_by(product_id: product_id)

    if current_item.present?
      current_item.quantity += 1
    else
      current_item = self.order_items.build(product_id: product_id)
    end

    current_item
  end

  def total_price
    order_items.to_a.sum { |item| item.total_price}
  end
end

# == Schema Information
#
# Table name: carts
#
#  id         :bigint           not null, primary key
#  email      :string
#  string     :string
#  tag        :string
#  token_key  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  require 'securerandom'
  require 'digest'
  include CurrentCart

  before_action :set_cart, only: [:index, :show, :edit, :update, :destroy, :send_confirm_order, :confirm_auth]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    # @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    respond_to do |format|
      format.html {}
      format.json {head :no_content}
      format.js {render layout: false}
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    if @cart.id == session[:cart_id]
      @cart.destroy
      session[:cart_id] = nil
    end
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def send_confirm_order
    user = User.find_by_email(params[:user_email])
    SendWelcomeEmailJob.perform_later(user) if user.present?
  end

  def confirm_auth

  end

  def confirm_email
    
  end

  private

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to '/', notice: 'Invalid cart'
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.require(:cart).permit(:token_key, :string, :email, :tag)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<table>
  <thead>
  <tr>
    <th class="mail-order-th" id="th-table-item-title">Item</th>
    <th class="mail-order-th-name">Name</th>
    <th class="center mail-order-th">Quantity</th>
    <th class="left mail-order-th" id="th-table-space-title">&nbsp;</th>
    <th class="mail-order-th">Price</th>
  </tr>
  </thead>
  <tbody>
  <% cart.order_items.order('created_at asc').each do |order_item| %>
      <tr>
        <td id="td-table-image-item">
          <%= image_tag order_item.product.image.url(:thumb), class: 'thumbnail-image-line-item-cart' %>
        </td>

        <td>
          <%= link_to order_item.product.name, category_product_path(order_item.product.category, order_item.product), target: :_blank %>
        </td>

        <td class="center">
          <%= order_item.quantity %>
        </td>

        <td id="td-adj-number">
          <div class="row row-adj-up-down">
            <div class="col s12 col-adj-product">
              <%= link_to '<i class="material-icons md-72 adj-quantity-cart">arrow_drop_up</i>&nbsp;'.html_safe, order_items_path + '/up/' + order_item.id.to_s, remote: true, method: :post %>
            </div>

            <div class="col s12">
              <%= link_to '<i class="material-icons md-72 adj-quantity-cart">arrow_drop_down</i>&nbsp;'.html_safe, order_items_path + '/down/' + order_item.id.to_s, remote: true, method: :post %>
            </div>
          </div>
        </td>

        <td>$<%= order_item.total_price %></td>

        <td class="center">
          <%= link_to '<i class="material-icons">delete</i>'.html_safe, order_items_path + '/' + order_item.id.to_s, remote: true,
                      method: :delete, data: {confirm: 'Are you sure?'}, class: 'destroy-line-item', title: 'Delete item' %>
        </td>
      </tr>
  <% end %>
  <tr class="total_line">
    <td>&nbsp;</td>
    <td class="td-table-space-total">&nbsp;</td>
    <td class="center"><b>Total</b></td>
    <td class="td-table-space-total">&nbsp;</td>
    <td class="total_cell"><b>$<%= cart.total_price.to_s %></b></td>

    <td class="center">
      <%= link_to '<i class="material-icons md-36" id="icon-delete-all-cart">delete_sweep</i>'.html_safe, carts_path + '/' + cart.id.to_s, method: :delete, data: {confirm: 'Are you sure?'}, title: 'Delete All' %>
    </td>
  </tr>
  </tbody>
</table>

<!-- ---------------------- -->
<div id="cart-user-info-larger">
  <% if !user_signed_in? %>
        <div class="row row-user-modal-cart">
          <div class="col s12">
            <div class="input-field center input-user-modal-cart">
              <p class="guide-message-steps-order">Step 1: Confirm the order by Google - Facebook - Twitter</p>
            </div>
          </div>
        </div>

        <div class="row center">
          <div class="col s12">
            <%= google_sign_in_button 'Sign in with my Google account', class:'loginBtn loginBtn--google', proceed_to: create_login_url %>
          </div>
        </div>
        <div class="row center">
          <div class="col s12">
            <%= link_to '<i class="fa fa-facebook"></i>&nbsp; &nbsp; Sign up with Facebook'.html_safe, user_facebook_omniauth_authorize_path, class: 'btn blue darken-4' %>
          </div>
        </div>
        <%= form_tag cart_send_confirm_order_path, id: 'user_info_form_no_modal', remote: true, authenticity_token: true, method: :post do %>
          <div class="row row-user-modal-cart">
            <div class="col s12">
              <div class="input-field center input-user-modal-cart">
                <p class="guide-message-steps-order">
                  Or confirm by email:</p>
              </div>
            </div>
          </div>

          <div class="row row-user-modal-cart">
            <div class="col s12">
              <div class="input-field center input-user-modal-cart">
                <span>Email: </span>
                <input autocomplete="on" class="edit_profile user-infomation-no-modal-cart" placeholder="Email" type="email" value="" name="user_email" id="user_email">
              </div>
            </div>
          </div>

          <div class="row row-user-modal-cart">
            <div class="col s12">
              <div class="input-field input-user-modal-cart">
                <p id="message_sent_email_confirm_order">Enter the email address and press
                  Confirm, then check the confirmation email (Inbox or Spam folder).</p>
              </div>
            </div>
          </div>

          <div class="row submit-user-in-cart">
            <div class="input-field col s12 center" id="button-submit-register-user-in-cart">
              <%= submit_tag('Confirm', id: 'payment-co-button', :class => 'btn pink darken-2 paybutton', :name => 'submit', title: 'Confirm email before to order') %>
            </div>
          </div>
      <% end %>
  <% else %>
      <% @user = User.find(current_user.id) %>
      <%= form_tag orders_path, id: 'user_info_form_no_modal', authenticity_token: true, method: :post do %>
          <div class="row row-user-modal-cart">
            <div class="col s12">
              <div class="input-field center input-user-modal-cart">
                <p class="guide-message-steps-order">Step 2: Enter user's information, please
                  check carefully before payment.</p>
              </div>
            </div>
          </div>

          <div class="users_information_container_cart">
            <div class="row">
              <div class="col s2 title-field-in-no-modal-cart" style="padding: 10px 0;">
                Name:
              </div>
              <div class="col s10">
                <input autocomplete="on" class="edit_profile user-infomation-no-modal-cart" placeholder="Name (minimum 3 chars)" type="text" name="user_name" id="user_name" value="<%= @user.name %>">
              </div>
            </div>

            <div class="row">
              <div class="col s2 title-field-in-no-modal-cart" style="padding: 10px 0;">
                Address:
              </div>
              <div class="col s10">
                <input id="user_address" class="edit_profile user-infomation-no-modal-cart" placeholder="Address - Can not blank" autofocus="autofocus" type="text" value="<%= @user.address %>" name="user_address">
              </div>
            </div>

            <div class="row">
              <div class="col s2 title-field-in-no-modal-cart" style="padding: 10px 0;">
                Phone:
              </div>
              <div class="col s10">
                <input id="user_phone" class="edit_profile user-infomation-no-modal-cart" placeholder="Phone - Can not blank" type="text" value="<%= @user.phone %>" name="user_phone">
              </div>
            </div>

            <div class="row">
              <div class="col s2 title-field-in-no-modal-cart" style="padding: 10px 0;">
                City:
              </div>
              <div class="col s10">
                <input id="user_city" class="edit_profile user-infomation-no-modal-cart" placeholder="City - Can not blank" autofocus="autofocus" type="text" value="<%= @user.city %>" name="user_city">
              </div>
            </div>

            <div class="row">
              <div class="col s2 title-field-in-no-modal-cart" style="padding: 10px 0;">
                Country:
              </div>
              <div class="col s10">
                <%= select_tag 'user_country', options_for_select(ISO3166::Country.all, selected: @user.country), class: 'select-country-cart' %>
              </div>
            </div>

            <div class="row">
              <div class="col s2 title-field-in-no-modal-cart" style="padding: 10px 0;">
                Zipcode:
              </div>
              <div class="col s10">
                <input id="user_zipcode" class="edit_profile user-infomation-no-modal-cart" placeholder="Zipcode - Can not blank" autofocus="autofocus" type="text" value="<%= @user.zipcode %>" name="user_zipcode">
              </div>
            </div>

            <input class="validate" type="hidden" name="user_check" id="user_info" value="UpdateUser">

            <div class="row">
              <div class="input-field col s12 center">
                <%= submit_tag('Checkout', id: 'payment-co-button-no-modal', :class => 'btn pink darken-2 paybutton', :name => 'submit', title: 'Fill users information before to order') %>
              </div>
            </div>
          </div>
      <% end %>
  <% end %>
</div>

<script>
    function ShowMessageNoteEmail() {
        $("#message_sent_email_confirm_order").css("color", "initial");
        $("#message_sent_email_confirm_order").css("font-size", "16px");
        $("#message_sent_email_confirm_order").css("font-weight", "normal");

        $("#message_sent_email_confirm_order").html("Enter the email address and press Confirm, then check the confirmation email (Inbox or Spam folder).");
    }

    $(document).ready(function () {
        $("#user_email").mouseup(ShowMessageNoteEmail);
        $("#user_email").keyup(ShowMessageNoteEmail);

        $('#user_info_form_no_modal').submit(function () {
            var allIsOk = true;

            // Check if empty of not
            $(this).find('input[type!="hidden"]').each(function () {
                if (!$(this).val()) {
                    allIsOk = false;
                }
            });

            return allIsOk
        });
    });
</script>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :token_key %>
    <%= form.text_field :token_key %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<div class="container" id="customize-container">
  <div class="row"></div>
  <div class="row">
    <% if @cart %>
      <%= render @cart %>
    <% end %>
  </div>
</div>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="container" id="customize-container">
  <div class="row"></div>
  <div class="row"></div>

  <div class="row">
    <% if @cart.present? %>
        <% unless @cart.order_items.empty? %>
            <div class="col s12 m12 l10 offset-l1" id="card-show-cart-no-modal">
              <div class="card">
                <div class="title-order-page">
                  Your cart
                </div>
                <div class="card-content">
                  <div class="cart">
                    <%= render @cart %>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
    <% else %>
        <p>The cart empty!</p>
    <% end %>
  </div>
</div>

app/views/carts/show.js.erb
$('.cart').html("<%=j render(@cart) %>");
$('#count-items-in-cart').html("<%=j @cart.items_count %>");
$('#count-items-in-cart-menu').html("<%=j @cart.items_count %>");

$('#modal-cart').modal('open');
$('#cart-icon-on-header').show();
$('#cart-icon-on-header-menu').show();